# Generated by Django 5.1.7 on 2025-06-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_cover_image_alter_recipestep_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('recipe', 'Recipe'), ('article', 'Article')], default='recipe', max_length=10),
        ),
    ]
